### ISSUE TITLE
Improve HFTS generation from meshes

### ISSUE THREAD

**Issue by JoshuaHaustein** [kth-ros-pkg/hfts_grasp_planner#3]
The current HFTS generation from meshes suffers severely from unbalanced point clouds. Hence, taking only the vertices from triangle meshes as points can lead to very poor HFTSs.

**Comment by JoshuaHaustein** [comment]
Addressed in b54ed7c8861c44f777fbea8c7f6a69468032587f.

**Comment by diogoalmeida** [comment]
Go back to your holidays!!!
